build:
  image: eu.gcr.io/test-k8s-1289/clock-node:10.14.1-build
  pull: true
  environment:
    - SHELL=/bin/bash
    - YARN_CACHE_FOLDER=/drone/yarn-cache
    - BABEL_CACHE_PATH=/drone/babel-cache.json
  auth_config:
    username: $$GCR_USER
    password: >
      {"type":"service_account","project_id":"test-k8s-1289","private_key_id":"41d13743672f887f73c3d9d7fd503a3793c4616d","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSWDCh9CblX4fm\nT+/3l+qqZp3h+BH3CqfuUIvVyFUt4NPUMXWFy7GvH/hiSmGmQuEcy0LLZuqhXwbq\nwkS4HmMDkwj4XN5lPim4caBToe0E0zbqTEODN0+/0y2GqdGFd8uRPuP9znz5xhhW\nj3TTiVD+tgmQ6kVyZ9/M6LOQME1hn/q6ABGqsdiZW3S1n6HltQxiZ3bD81fiwysm\nbQ/IGnH3UDypnnxqQ0CQOh1Au+Yn+nsh2CCE2nazMknXh9188WUclFpXOsWQGj2i\nRePtYqsIOevpWN5Au/+E1dOE1iREqvihqfadFFInqJkks9qs6ijxOXklkEZTr0Z7\nSAtbsLeHAgMBAAECggEAFnUUGXZHFcHgL/aqY3tbloSiy89uqlNnS8nue4L/l0e+\nGfzxBPQqMy6bxjGV5Ja0xt9mQ6JqdRMJE7N2Ki73kM/ae4p80lqEunotWUgrACeN\ncMz9O0Ccq1ozzUt4DJxCj+pvwD4UrZu5lmbzTZbv5/Z1Z1icCZ9pF5/KFmFjLozJ\n4p335HM+zlRzdraxIb6sXafQovaT9PbqmPy0WL7SnCQieoI+UWgT3QqfA7v0NBNv\nPsEyQvZIniITKhsdwhl+INVha0C50t/MGg43vmWeCUHUPJHiVfNSEgXTouWtPhdo\nEIuVnVkIEF3HLfcJMTO+Qradtd8FJYzx80PnxQ7AqQKBgQD6UQso+H7gef8qkvui\nJcZ7PAK5gapHX8Do5DywfjNAKJDTDgp57gNxhT7FzTZzSPkrmJ/svjH8KjAPVWWk\ny/HycHw5O3FGeS2F63hZTVZf/q6BuOfAuR5JoCy0PUTrqEH8C+1ilL8f2ebaky05\n/+3uFvIeXGQ6X5ZxEl3Z0zzkhQKBgQCVqs/ve12gCKxzzQGgSGAKymUWlfnGRXzP\nVQSUzxQwljGC17Ww4sWEOldPCsZvylHKenhMG1uxIBdmQr5qjVRCBQVPzVtZ4njF\naZ2QactfQG3F0RWvCMHurKMSlaerNwG2Th2OsFGYzO79RTtnhf1woJNaKZojgp3f\nqaz/voFfmwKBgQDUpx0QBWvkUEASbyQPMIBaGTVHW3zJffNo5t0YI15u1weSBY+o\n3idWvZgCesATWJ82Bkd23G2iiESkAiyDwC8fg6hFBtbIxBGEf/KSCz2h979QvUFF\nXP76FXVk+dgfS6Yi9g8JfMyRxpB0iCwX5fDAIAY4/My5OpOYI75PW0GT8QKBgDcR\nJvqVKGiGaHUe+7cuie/Ocg0yVzlFPdvHCy15V5Nc35Clr1sKxOOW16LkcwiUpy1Z\njENsWXs9NH7Sld78awDzefXXuAHFWuw/pNKKqmI8gWckO9cv4LLhYAqpd4x+a6nY\n6fUjGJKg7FnRjD7VxN8Ypb6pyeXA3Dd75YQfYth7AoGAWePCAgXDyYAgQIYbaM+W\nIE9r/u7i0Sw4Z+gJB3HN8xpQQkhPktyg23xewjhq3LK3+2mMMm+A/06EtykzN38V\nsWWsT9hic7ggf29yrUEd/7eaDfmK5lmhPt24V/9P0px9dudfa5VSeNn71B4Chzaa\nQ7tSLprDVP0VpAWXdRpv2KQ=\n-----END PRIVATE KEY-----\n","client_email":"drone-gcr@test-k8s-1289.iam.gserviceaccount.com","client_id":"107287920262838646138","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/drone-gcr%40test-k8s-1289.iam.gserviceaccount.com"}
  commands:
    - apt-get install libX11-6
    - yarn install --silent --no-emoji --prefer-offline
    - yarn test:percy
compose:
  database:
    image: mongo:3.4
    command: --smallfiles
cache:
  mount:
    - .git
    - .eslintcache
    - /drone/babel-cache.json
    - /drone/yarn-cache
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: frontend-seniors
    username: drone
